name: excess deaths

on:
  schedule:
    # says run at the 24th min, 21th hr UTC (5:24pm ET) of every day
    # also fyi, midnight is just 0 and 1 am is 1
    - cron: '35 21 * * *'

jobs:
  excess:
    name: excess chart font test
    runs-on: [ubuntu-latest]
    
    # env vars for rtweet; 1 old one just to pull tweets; 2 others to tweet from accts
    env:
      APPNAME: ${{ secrets.APPNAME }}
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
      ACCESSSECRET: ${{ secrets.ACCESSSECRET }}
      APPNAMEE: ${{ secrets.APPNAMEE }}
      APIKEYE: ${{ secrets.APIKEYE }}
      APISECRETE: ${{ secrets.APISECRETE }}
      ACCESSTOKENE: ${{ secrets.ACCESSTOKENE }}
      ACCESSSECRETE: ${{ secrets.ACCESSSECRETE }}
      APPNAMEF: ${{ secrets.APPNAMEF }}
      APIKEYF: ${{ secrets.APIKEYF }}
      APISECRETF: ${{ secrets.APISECRETF }}
      ACCESSTOKENF: ${{ secrets.ACCESSTOKENF }}
      ACCESSSECRETF: ${{ secrets.ACCESSSECRETF }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    
    steps:
      
      # copy repo  
      - uses: actions/checkout@v2
      
      # installs r
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.2'
      
      # need libcurl to install RCurl pkg on Linux
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      
      # need these for rgdal package
      - name: Install gdal, proj, and geos
        run: sudo apt-get install libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev
      
      # needed for units package
      - name: Install udunits2
        run: sudo apt-get install libudunits2-dev
      
      # installs pandoc for rmarkdown
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: install fonts
        run: Rscript -e 'library(extrafont); font_import(paths = glue::glue("{rprojroot::find_rstudio_root_file()}/font"), prompt=FALSE); loadfonts()'
      
      - name: run excess-death-col
        run: Rscript "R/excess-death-col.R"
        
      ## Commit, Push, Trigger other repo workflow
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "6:30pm charts update" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        # GITHUB_TOKEN automatically created
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
        