name: Sel Test

on:
  schedule:
    # says run at the 38th min, 21th hr UTC (5:54pm ET) of every day
    - cron: '50 0 * * *'

jobs:
  update:
    name: test running RSelenium
    runs-on: [ubuntu-latest]
    steps:
      # must checkout out of own repo to use "action" in someone elses  
      - uses: actions/checkout@v2
      # installs r
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.2'
      # need libcurl to install RCurl pkg on Linux
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      # need these for rgdal package
      - name: Install gdal, proj, and geos
        run: sudo apt-get install libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev
      # needed for units package
      - name: Install udunits2
        run: sudo apt-get install libudunits2-dev
      - name download a jar
        run: wget "https://selenium-release.storage.googleapis.com/4.0-alpha-6/selenium-server-4.0.0-alpha-6.jar"
      # installs pandoc for rmarkdown
      - uses: r-lib/actions/setup-pandoc@v1
      - name: install RSelenium separately
        run: Rscript -e "install.packages('RSelenium', repos = 'https://cloud.r-project.org')"
      - name: install stringi
        run: Rscript -e "install.packages('stringi', repos = 'https://cloud.r-project.org')"
      - name: run RSelenium script
        run: Rscript "R/sel-test.R"